from aiogram.types import KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove, \
                          InlineKeyboardButton, InlineKeyboardMarkup



material = ReplyKeyboardMarkup(one_time_keyboard=True)
First = KeyboardButton("Я пишу сочинение, эссе, письменную работу")
Second = KeyboardButton("Я хочу перевести текст")
Third = KeyboardButton("Не знаю")
material.add(First).add(Second).add(Third)
keyboard_markup = InlineKeyboardMarkup()
notes = InlineKeyboardButton('Заметки', callback_data='notes')
translator = InlineKeyboardButton('Переводчик', callback_data='translator')
link_library = InlineKeyboardButton('Библиотека ссылок', callback_data='link_library')
keyboard_markup.row(link_library, notes)
keyboard_markup.add(translator)
back_button = InlineKeyboardButton("Вернуться назад", callback_data='back')
back_keyboard = InlineKeyboardMarkup().add(back_button)
add_button = InlineKeyboardButton("Добавить новую заметку", callback_data='add_note')
notes_keyboard = InlineKeyboardMarkup()
change_name = InlineKeyboardButton("Изменить имя", callback_data='change_name')
change_content = InlineKeyboardButton("Изменить содержимое", callback_data='change_content')
read_content = InlineKeyboardButton("Прочитать заметку", callback_data='read_content')
change_keyboard = InlineKeyboardMarkup().add(change_name).add(change_content).add(read_content)
del_button = InlineKeyboardButton('Удалить заметку', callback_data='delete_note')
french = KeyboardButton("Французский")
german = KeyboardButton("Немецкий")
russian = KeyboardButton("Русский")
english = KeyboardButton("Английский")
chinese = KeyboardButton("Китайский")
languages = ReplyKeyboardMarkup(one_time_keyboard=True)
languages.add(french).add(german).add(russian).add(english).add(chinese)